# Generated by Django 5.2.15 on 2026-07-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auditlog'),
        ('expenses', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkflow',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflows', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='agentworkflow',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflows', to='expenses.receipt'),
        ),
    ]
