# Generated by Django 5.2.16 on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agentworkflow_invoice_alter_agentworkflow_receipt"),
        ("expenses", "0002_expenseapprovalpolicy_expense_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentworkflow",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_workflows",
                to="expenses.expense",
            ),
        ),
    ]
