# Generated by Django 5.2.16 on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("tenancy", "0002_tenantmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseApprovalPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("approval_queue", models.CharField(default="Finance", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={"ordering": ["priority", "id"]},
        ),
        migrations.AddField(
            model_name="expense",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("not_requested", "Not requested"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_requested",
                max_length=20,
            ),
        ),
    ]
